# SwiftLint Configuration for Akusti-Scan-App-RT60

# Rules
disabled_rules:
  - trailing_whitespace
  - line_length # We use 120 character limit
  - force_cast # Sometimes necessary
  - force_try # OK in specific cases with good reason

opt_in_rules:
  - empty_count
  - empty_string
  - explicit_init
  - fatal_error_message
  - first_where
  - closure_spacing
  - contains_over_first_not_nil
  - discouraged_object_literal
  - empty_xctest_method
  - explicit_self
  - extension_access_modifier
  - fallthrough
  - file_header
  - file_name
  - identical_operands
  - implicit_return
  - joined_default_parameter
  - let_var_whitespace
  - literal_expression_end_indentation
  - lower_acl_than_parent
  - modifier_order
  - multiline_arguments
  - multiline_function_chains
  - multiline_literal_brackets
  - multiline_parameters
  - number_separator
  - operator_usage_whitespace
  - overridden_super_call
  - override_in_extension
  - pattern_matching_keywords
  - private_action
  - private_outlet
  - prohibited_super_call
  - quick_discouraged_call
  - redundant_nil_coalescing
  - redundant_type_annotation
  - sorted_first_last
  - static_operator
  - toggle_bool
  - unavailable_function
  - unneeded_parentheses_in_closure_argument
  - vertical_parameter_alignment_on_call
  - vertical_whitespace_closing_braces
  - vertical_whitespace_opening_braces
  - yoda_condition

# Paths
included:
  - Akusti-Scan-App-RT60
  - Akusti-Scan-App-RT60Tests
  - Akusti-Scan-App-RT60UITests

excluded:
  - Pods
  - Carthage
  - .build
  - DerivedData
  - fastlane
  - Akusti-Scan-App-RT60.xcodeproj

# Metrics
line_length:
  warning: 120
  error: 150
  ignores_comments: true
  ignores_urls: true
  ignores_function_declarations: false
  ignores_interpolated_strings: true

file_length:
  warning: 500
  error: 1000
  ignore_comment_only_lines: true

function_body_length:
  warning: 50
  error: 100

function_parameter_count:
  warning: 6
  error: 8

type_body_length:
  warning: 300
  error: 500

large_tuple:
  warning: 3
  error: 4

cyclomatic_complexity:
  warning: 10
  error: 20
  ignores_case_statements: true

nesting:
  type_level:
    warning: 2
    error: 3
  statement_level:
    warning: 5
    error: 10

# Naming
identifier_name:
  min_length:
    warning: 2
    error: 1
  max_length:
    warning: 50
    error: 60
  excluded:
    - id
    - x
    - y
    - z
    - i
    - db
    - hz
    - rt
    - dB

type_name:
  min_length: 3
  max_length: 50
  excluded:
    - RT60

# Custom Rules
custom_rules:
  comment_spacing:
    name: "Comment Spacing"
    regex: '(^ *//\w+)'
    message: "There should be a space after //"
    severity: warning

  double_space:
    name: "Double Space"
    regex: '([a-z,A-Z] \s+)'
    message: "Double space detected"
    severity: warning

  empty_line_after_guard:
    name: "Empty Line After Guard"
    regex: '(^ *guard[ a-zA-Z0-9=?.\(\),><!]*\{[ a-zA-Z0-9=?.\(\),><!]*\}\n *(?!(?:return|guard|case|default)))'
    message: "There should be an empty line after a guard"
    severity: warning

  empty_line_after_super:
    name: "Empty Line After Super"
    regex: '(^ *super\.[ a-zA-Z0-9=?.\(\)\{\}:,><!]*\n *(?!(?:\}|return)))'
    message: "There should be an empty line after super"
    severity: warning

  unnecessary_type:
    name: "Unnecessary Type"
    regex: '[ a-zA-Z0-9]*(?:let|var) [ a-zA-Z0-9]*: ([a-zA-Z0-9]*)[\? ]*= \1'
    message: "Type definition not necessary"
    severity: warning

# Reporter
reporter: "xcode"

# Analyzer Rules (requires full project compilation)
analyzer_rules:
  - unused_import
  - unused_declaration
